### ISSUE TITLE
Bundler::GemNotFound

### ISSUE THREAD

**Issue by x1wins** [huacnlee/social-share-button#186]
Hello
i use rails 6.0.0 and docker-compose

i have run bundle install on docker-compose
and run generate social_share_button:install on docker-compose too
but not working
```
docker-compose run web bundle install 
docker-compose run web rails generate social_share_button:install
```

```
web_1  | bundler: failed to load command: rails (/usr/local/bundle/bin/rails)
web_1  | Bundler::GemNotFound: Could not find coffee-script-source-1.12.2 in any of the sources
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `map!'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `materialize'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:170:in `specs'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:237:in `specs_for'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:226:in `requested_specs'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:108:in `block in definition_method'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:20:in `setup'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler.rb:107:in `setup'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
web_1  |   /usr/local/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
blog_web_1 exited with code 1
```

**Comment by x1wins** [comment]
i found solve
i have run $ rm -ff Gemfile.lock and rebuild on docker-compose $ docker-compose up --build
close issue
